language: go
go:
    - 1.4
    - tip
before_install:
    - go get github.com/mattn/gom
    - go get golang.org/x/tools/cmd/cover
install:
    - gom install -v ./...
script: 
    - gom test  -v -cover ./... 
